version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: 03:00
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: 03:00
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: 03:00
