DISABLE:
  - SPELL

ENABLE_LINTERS:
  - GO_REVIVE
  - DOCKERFILE_HADOLINT
  - REPOSITORY_DUSTILOCK
  - REPOSITORY_GITLEAKS
  - REPOSITORY_SECRETLINT
  - REPOSITORY_TRIVY

GO_REVIVE_ARGUMENTS: -config revive.toml -exclude vendor/...
REPOSITORY_DUSTILOCK_ARGUMENTS: -r

