DISABLE:
  - SPELL

ENABLE_LINTERS:
  - GO_REVIVE
  - DOCKERFILE_HADOLINT
  - REPOSITORY_GITLEAKS
  - REPOSITORY_SECRETLINT
  - REPOSITORY_TRIVY

GO_REVIVE_ARGUMENTS: -config revive.toml -exclude vendor/...
