name: Build and release binaries

on:
  workflow_run:
    workflows:
      - Run MegaLinters
    types:
      - completed
    branches:
      - main

env:
  GO_VERSION: 1.22.5

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-and-release-binaries:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    strategy:
      matrix:
        goos:
          - x
        goarch:
          - x

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build cf-dyndns
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} OUTPUT_FILE_NAME=cf-dyndns-${{ matrix.goos }}-${{ matrix.goarch }} make build

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: cf-dyndns
          path: out
