name: Run MegaLinter

on:
  push:

  pull_request:
    branches:
      - main

env:
  GO_REVIVE_ARGUMENTS: -exclude vendor/...

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  megalinter:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: MegaLinter
        uses: oxsecurity/megalinter@v7
        env:
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE: SPELL
          ENABLE_LINTERS: GO_REVIVE,DOCKERFILE_HADOLINT,REPOSITORY_DUSTILOCK,REPOSITORY_GITLEAKS,REPOSITORY_SECRETLINT,REPOSITORY_TRIVY
